require("beatzball.plugins-setup")
require("beatzball.core.options")
require("beatzball.core.keymaps")
require("beatzball.core.alpha-theme")
require("beatzball.core.colorscheme")
require("beatzball.plugins.comment")
require("beatzball.plugins.nvim-tree")
require("beatzball.plugins.lualine")
require("beatzball.plugins.telescope")
require("beatzball.plugins.nvim-cmp")
require("beatzball.plugins.lsp.mason")
require("beatzball.plugins.lsp.lspsaga")
require("beatzball.plugins.lsp.lspconfig")
require("beatzball.plugins.lsp.null-ls")
require("beatzball.plugins.autopairs")
require("beatzball.plugins.treesitter")
require("beatzball.plugins.gitsigns")
require("beatzball.plugins.which-key")
require("beatzball.plugins.galaxyline")
require("beatzball.plugins.bufferline")

require("beatzball.plugins.staline")
require("beatzball.plugins.stabline")
-- require("beatzball.core.gui")
